package vista;

import controlador.CoordinadorCuarentenario;
import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.LogicaCuarentenario;
import maps.java.MapsJava;
import maps.java.ShowMaps;
import modeloBO.CuarentenarioBO;
import modeloBO.UsuarioBO;
import sizin.Box;
import sizin.ClaseObjetoParaComboBox;
import sizin.ClaseObjetoParaLista;
import sizin.ConfiguracionGlobal;
import sizin.JFrameConFondo;
import sizin.JLabelImagenAjusta;
import sizin.JTextFieldLimit;
import sizin.Lista;
import sizin.MyRenderer;
import sizin.Reloj;
import sizin.Tabla;
import sizin.URLabel;
import sizin.Ubicacion;

/**
 *
 * @author Erneski Coronado
 */
public class Epidemiologia extends JFrameConFondo {

    private Lista tax = new Lista();
    private URLabel label;
    ConfiguracionGlobal config = new ConfiguracionGlobal();

    private ClaseObjetoParaLista taxo = null;
    Tabla cua = new Tabla();
    Tabla inc= new Tabla();
    LogicaCuarentenario miLogicaCua;
    CoordinadorCuarentenario miCoordinadorCuarentenario;
    private Epidemiologia miVentanaEpi;
    Integer id_cuarentena=0;
    private Box comboestado = new Box();
    Ubicacion ObjUbicacion=new Ubicacion();
    
    /**
     * Creates new form Epidemiologia
     */
    public Epidemiologia() {
        MapsJava.setKey("AIzaSyCzWaJYw_MW87ganzyaVlxB9igfGMTTrW8");
        initComponents();
        setImagen("imagenes/fondo_difuminado.jpg");//se pasa la imagen de fondo del formulario
        JLabelImagenAjusta logo = new JLabelImagenAjusta();
        logo.ImagenJLabel(jLabelLogo, "imagenes/logo_sistema.png");
        jLabelLogo_des.setText(JLabelImagenAjusta.convertToMultiline("SISTEMA DE INFORMACIÓN PARA EL REGISTRO Y ANALISIS\n"
                + "DE MUESTRAS ZOOPATÓGENAS DE LA RED DE \n"
                + "LABORATORIOS DE DIAGNÓSTICO ZOOSANITARIO DEL INSAI\n"));
        Reloj r = new Reloj();
        jLabelFechaRG.setText(r.Hora());
        label = new URLabel();
        //tax= new Lista();
        tax.consultalist(config.lista_taxon_inicial, "tax.tsn", "tax.nombre_completo", "tax.rango_id", "ran.rango");//cargamos la consulta para cargar la especie
        tax.LLenarLista();//llenamos el combo de la especie
        cua.crearmodelocuarentenario();
        cua.columnastabla(4, config.tabla_cuarentenario);
        cua.LlenarTabla();
        inc.crearmodeloinciencias();
                                Integer tam_inc[] = {70,180,160,220,100,100,160,120,120,100,120,140,160,80,80,70,160,100,100};
                        for (int i = 0; i < 19; i++) {
           jTableIncidencias.getColumnModel().getColumn(i).setPreferredWidth(tam_inc[i]);
            jTableIncidencias.getColumnModel().getColumn(i).setHeaderRenderer(new MyRenderer(Color.CYAN.brighter(), Color.BLACK.darker()));
        }
        jTableCuarentenarios.setModel(cua.getModelo());
       
        jTextFieldNombreComun.setDocument(new JTextFieldLimit(45, false));
        jTextFieldDescripcion.setDocument(new JTextFieldLimit(255, false));
        jInternalFrameOrganismos.setVisible(false);
        comboestado.consultabox2(config.box_consulta_estado, "id_estado", "estado");
        comboestado.LLenarBoxConID();
        jComboBoxEstado.setModel(comboestado.getModelo());

        Integer tam_detalle[] = {80, 160, 160, 250};
        for (int i = 0; i < 4; i++) {
            jTableCuarentenarios.getColumnModel().getColumn(i).setPreferredWidth(tam_detalle[i]);
            jTableCuarentenarios.getColumnModel().getColumn(i).setHeaderRenderer(new MyRenderer(Color.CYAN.brighter(), Color.BLACK.darker()));
        }

    }

    private void iniciarCuarentena() {
        /*Se instancian las clases*/
        miLogicaCua = new LogicaCuarentenario();
        miCoordinadorCuarentenario = new CoordinadorCuarentenario();
        /*Se establecen las relaciones entre clases*/
        this.setCoordinadorCuarentenario(miCoordinadorCuarentenario);
        miLogicaCua.setCoordinador(miCoordinadorCuarentenario);
        miCoordinadorCuarentenario.setMiVentanaConfiguracion(miVentanaEpi);
        miCoordinadorCuarentenario.setMiLogica(miLogicaCua);
    }

    public void setCoordinadorCuarentenario(CoordinadorCuarentenario miCoordinador) {
        this.miCoordinadorCuarentenario = miCoordinador;
    }
    
        private void iniciar() {
        /*Se instancian las clases*/
        miVentanaEpi = new Epidemiologia();
        miVentanaEpi.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFechaRG = new javax.swing.JLabel();
        jLabelLogo_des = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jPanelBotonesSolicitud = new javax.swing.JPanel();
        jButtonAbrirOrganismos = new javax.swing.JButton();
        jButtonAbrirBuscarIncidencia = new javax.swing.JButton();
        jSeparatorSolicitudes = new javax.swing.JSeparator();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jInternalFrameOrganismos = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCuarentenarios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListTaxon = new javax.swing.JList();
        jButtonTaxReset = new javax.swing.JButton();
        jTextFieldNombreComun = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonTax = new javax.swing.JButton();
        jPanelUrl = new javax.swing.JPanel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jInternalFrameIncidencias = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableIncidencias = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox();
        jButtonBuscar = new javax.swing.JButton();
        jButtonMapa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SIZOIN - Epidemiología");
        setExtendedState(6);

        jLabelFechaRG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFechaRG.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFechaRG.setText("jLabel1");

        jLabelLogo_des.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabelLogo_des.setForeground(new java.awt.Color(255, 102, 102));
        jLabelLogo_des.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanelBotonesSolicitud.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBotonesSolicitud.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonAbrirOrganismos.setBackground(new java.awt.Color(204, 255, 204));
        jButtonAbrirOrganismos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar32.png"))); // NOI18N
        jButtonAbrirOrganismos.setToolTipText("Agregar Organismos Cuarentenarios en Venezuela");
        jButtonAbrirOrganismos.setBorderPainted(false);
        jButtonAbrirOrganismos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAbrirOrganismosMouseClicked(evt);
            }
        });

        jButtonAbrirBuscarIncidencia.setBackground(new java.awt.Color(204, 204, 255));
        jButtonAbrirBuscarIncidencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar32.png"))); // NOI18N
        jButtonAbrirBuscarIncidencia.setToolTipText("Consultar Incidencias Epidemiológicas");
        jButtonAbrirBuscarIncidencia.setBorderPainted(false);
        jButtonAbrirBuscarIncidencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAbrirBuscarIncidenciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAbrirBuscarIncidenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAbrirBuscarIncidenciaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesSolicitudLayout = new javax.swing.GroupLayout(jPanelBotonesSolicitud);
        jPanelBotonesSolicitud.setLayout(jPanelBotonesSolicitudLayout);
        jPanelBotonesSolicitudLayout.setHorizontalGroup(
            jPanelBotonesSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesSolicitudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonesSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAbrirBuscarIncidencia)
                    .addComponent(jButtonAbrirOrganismos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotonesSolicitudLayout.setVerticalGroup(
            jPanelBotonesSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesSolicitudLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jButtonAbrirOrganismos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAbrirBuscarIncidencia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1200, 481));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(745, 481));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(780, 481));

        jInternalFrameOrganismos.setClosable(true);
        jInternalFrameOrganismos.setTitle("Organismos Cuarentenarios");
        jInternalFrameOrganismos.setMaximumSize(new java.awt.Dimension(757, 457));
        jInternalFrameOrganismos.setMinimumSize(new java.awt.Dimension(757, 457));
        jInternalFrameOrganismos.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Organismos Cuarentenarios Registrados"));

        jTableCuarentenarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCuarentenariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCuarentenarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jListTaxon.setModel(tax.modelo);
        jListTaxon.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListTaxonValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jListTaxon);

        jButtonTaxReset.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTaxReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/refrescar.png"))); // NOI18N
        jButtonTaxReset.setToolTipText("Resetear Taxonomía");
        jButtonTaxReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaxResetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Descripción:");

        jButtonTax.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        jButtonTax.setToolTipText("Buscar Hijos del Taxon");
        jButtonTax.setPreferredSize(new java.awt.Dimension(32, 32));
        jButtonTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaxActionPerformed(evt);
            }
        });

        jPanelUrl.setBackground(new java.awt.Color(255, 255, 255));
        jPanelUrl.setBorder(javax.swing.BorderFactory.createTitledBorder("Ayuda Taxonómica"));

        javax.swing.GroupLayout jPanelUrlLayout = new javax.swing.GroupLayout(jPanelUrl);
        jPanelUrl.setLayout(jPanelUrlLayout);
        jPanelUrlLayout.setHorizontalGroup(
            jPanelUrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );
        jPanelUrlLayout.setVerticalGroup(
            jPanelUrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nombre Común:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNombreComun, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDescripcion))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonTax, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTaxReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jPanelUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonTax, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTaxReset))
                    .addComponent(jPanelUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombreComun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar.png"))); // NOI18N
        jButton1.setToolTipText("Agregar el organismo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/papelera32.png"))); // NOI18N
        jButtonEliminar.setToolTipText("Eliminar el organismo");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jInternalFrameOrganismosLayout = new javax.swing.GroupLayout(jInternalFrameOrganismos.getContentPane());
        jInternalFrameOrganismos.getContentPane().setLayout(jInternalFrameOrganismosLayout);
        jInternalFrameOrganismosLayout.setHorizontalGroup(
            jInternalFrameOrganismosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrameOrganismosLayout.setVerticalGroup(
            jInternalFrameOrganismosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jInternalFrameIncidencias.setClosable(true);
        jInternalFrameIncidencias.setTitle("Organismos Cuarentenarios");
        jInternalFrameIncidencias.setMaximumSize(new java.awt.Dimension(757, 457));
        jInternalFrameIncidencias.setMinimumSize(new java.awt.Dimension(757, 457));
        jInternalFrameIncidencias.setVisible(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Incidencias Epidemiológicas"));

        jScrollPane2.setAutoscrolls(true);

        jTableIncidencias.setModel(inc.modelo);
        jTableIncidencias.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableIncidencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableIncidenciasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableIncidencias);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Estado:");

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        jButtonBuscar.setToolTipText("Agregar el organismo");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonMapa.setBackground(new java.awt.Color(255, 255, 255));
        jButtonMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/globo16.png"))); // NOI18N
        jButtonMapa.setToolTipText("Visualizar en mapa");
        jButtonMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMapaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jInternalFrameIncidenciasLayout = new javax.swing.GroupLayout(jInternalFrameIncidencias.getContentPane());
        jInternalFrameIncidencias.getContentPane().setLayout(jInternalFrameIncidenciasLayout);
        jInternalFrameIncidenciasLayout.setHorizontalGroup(
            jInternalFrameIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrameIncidenciasLayout.setVerticalGroup(
            jInternalFrameIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrameOrganismos, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(482, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jInternalFrameIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrameOrganismos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jInternalFrameIncidencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1.setLayer(jInternalFrameOrganismos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jInternalFrameIncidencias, javax.swing.JLayeredPane.DEFAULT_LAYER);

        try {
            jInternalFrameIncidencias.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelFechaRG, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLogo_des, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 505, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelBotonesSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparatorSolicitudes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFechaRG, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLogo_des, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelBotonesSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 364, Short.MAX_VALUE))
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbrirOrganismosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAbrirOrganismosMouseClicked
        jInternalFrameOrganismos.setVisible(true);
        jInternalFrameOrganismos.toFront();
    }//GEN-LAST:event_jButtonAbrirOrganismosMouseClicked

    private void jButtonAbrirBuscarIncidenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAbrirBuscarIncidenciaMouseClicked
        jInternalFrameIncidencias.setVisible(true);
        jInternalFrameIncidencias.toFront();
    }//GEN-LAST:event_jButtonAbrirBuscarIncidenciaMouseClicked

    private void jButtonAbrirBuscarIncidenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAbrirBuscarIncidenciaMouseEntered
        /* jLabelImagenAjusta aju=new jLabelImagenAjusta();
         aju.ImagenJLabel(jLabelvisualizar, "iconos/presentabuscarregistro.jpg");*/
    }//GEN-LAST:event_jButtonAbrirBuscarIncidenciaMouseEntered

    private void jButtonAbrirBuscarIncidenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAbrirBuscarIncidenciaMouseExited

    }//GEN-LAST:event_jButtonAbrirBuscarIncidenciaMouseExited

    private void jButtonTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaxActionPerformed
        ClaseObjetoParaLista taxo_1 = (ClaseObjetoParaLista) jListTaxon.getSelectedValue(); //creamos objeto para extraer el id
        Integer tsn = taxo_1.getId();
        tax.consultalist(config.taxonomia(tsn), "tax.tsn", "tax.nombre_completo", "tax.rango_id", "ran.rango");//cargamos la consulta para cargar la especie
        tax.LLenarLista();//llenamos el combo de la especie
    }//GEN-LAST:event_jButtonTaxActionPerformed

    private void jListTaxonValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTaxonValueChanged
        taxo = (ClaseObjetoParaLista) jListTaxon.getSelectedValue(); //creamos objeto para extraer el id
        @SuppressWarnings("UnusedAssignment")
        String url = null;//hay que limpiarlo para que lo muestre vacio
        jPanelUrl.add(label);
        label.setLocation(10, 30);
        if (taxo != null) {
            url = "http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=" + taxo.getId();
            label.setURL(url);
            label.setText("Rango Taxonomico: " + taxo.getRango() + ", Mas sobre " + taxo.getNombre());
            label.setSize(350, 15);
        }
    }//GEN-LAST:event_jListTaxonValueChanged

    private void jButtonTaxResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaxResetActionPerformed
        tax.consultalist(config.lista_taxon_inicial, "tax.tsn", "tax.nombre_completo", "tax.rango_id", "ran.rango");//cargamos la consulta para cargar la especie
        tax.LLenarLista();//llenamos el combo de la especie
        label.setURL("");
        label.setText("");
    }//GEN-LAST:event_jButtonTaxResetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
                try {
            this.iniciarCuarentena();
            CuarentenarioBO miCuarentena = new CuarentenarioBO();
            miCuarentena.setId_tsn(taxo.getId());
            miCuarentena.setNombre_comun(jTextFieldNombreComun.getText());
            miCuarentena.setDescripcion(jTextFieldDescripcion.getText());

            if (miCoordinadorCuarentenario.registrarOrganismo(miCuarentena) == true) {
                jTextFieldNombreComun.setText(null);
                jTextFieldDescripcion.setText(null);
                cua.LlenarTabla();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error en el Ingreso de Datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        this.iniciarCuarentena();
                if (id_cuarentena != null) {
            this.iniciarCuarentena();
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "Desea eliminar el organismo seleccionado de la lista cuarentenaria?", "Confirmacion",
                    JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_NO_OPTION) {
                if (miCoordinadorCuarentenario.eliminarOrganismo(id_cuarentena) == true) {
                    cua.LlenarTabla();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione en la tabla el usuario a eliminar", "Informacion", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTableCuarentenariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCuarentenariosMouseClicked
        id_cuarentena = Integer.parseInt(jTableCuarentenarios.getModel().getValueAt(jTableCuarentenarios.getSelectedRow(), 0).toString());

    }//GEN-LAST:event_jTableCuarentenariosMouseClicked

    private void jTableIncidenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableIncidenciasMouseClicked
        ObjUbicacion.setLatitud(Double.parseDouble(jTableIncidencias.getModel().getValueAt(jTableIncidencias.getSelectedRow(), 14).toString()));
        ObjUbicacion.setLongitud(Double.parseDouble(jTableIncidencias.getModel().getValueAt(jTableIncidencias.getSelectedRow(), 13).toString()));
    }//GEN-LAST:event_jTableIncidenciasMouseClicked

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        if (jComboBoxEstado.getSelectedIndex() != 0) {
                            
                    String sql;

                        ClaseObjetoParaComboBox estado = (ClaseObjetoParaComboBox) jComboBoxEstado.getSelectedItem();//variable para extraer el id del tipo de analisis
                        String est = estado.getNombre();
                        sql = config.tabla_consulta_incidencias(est);
                        
                        //jTableIncidencias.setModel(inc.getModelo());


                    //if (miCoordinadorCuarentenario.buscarRegistro(sql) == true) {
                        inc.columnastabla(19, sql);
                        inc.LlenarTabla();
                    //} else {
                        //JOptionPane.showMessageDialog(null, "Este estado no reporta incidencias");
                    //}
                
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMapaActionPerformed
        ShowMaps ObjShow=new ShowMaps();
        
        //String direccionMapa=ObjShow.getURLMap(ObjUbicacion.getDireccion());       
        String coordenadas="https://www.google.co.ve/maps/@"+ObjUbicacion.getLatitud()+","+ObjUbicacion.getLongitud()+",14z?hl=es";
        try {
            try {
                //JOptionPane.showMessageDialog(rootPane, coordenadas, coordenadas, WIDTH, null);
                Desktop.getDesktop().browse(new URI(coordenadas));
            } catch (IOException ex) {
                Logger.getLogger(Epidemiologia.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(Epidemiologia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonMapaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Epidemiologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Epidemiologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Epidemiologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Epidemiologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Epidemiologia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAbrirBuscarIncidencia;
    private javax.swing.JButton jButtonAbrirOrganismos;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonMapa;
    private javax.swing.JButton jButtonTax;
    private javax.swing.JButton jButtonTaxReset;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JInternalFrame jInternalFrameIncidencias;
    private javax.swing.JInternalFrame jInternalFrameOrganismos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFechaRG;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLogo_des;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList jListTaxon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelBotonesSolicitud;
    private javax.swing.JPanel jPanelUrl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparatorSolicitudes;
    private javax.swing.JTable jTableCuarentenarios;
    private javax.swing.JTable jTableIncidencias;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldNombreComun;
    // End of variables declaration//GEN-END:variables
}
